//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.09 at 04:42:51 PM CEST 
//


package util;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bd" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Informations">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Titre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Serie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Identifiant" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Scenario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Dessin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Couleurs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Editeur" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ISBN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Image">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Description">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bd"
})
@XmlRootElement(name = "bds")
public class Bds {

    @XmlElement(required = true)
    protected List<Bds.Bd> bd;

    /**
     * Gets the value of the bd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bds.Bd }
     * 
     * 
     */
    public List<Bds.Bd> getBd() {
        if (bd == null) {
            bd = new ArrayList<Bds.Bd>();
        }
        return this.bd;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Informations">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Titre" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Serie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Identifiant" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Scenario" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Dessin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Couleurs" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Editeur" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ISBN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Image">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Description">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "informations",
        "image",
        "description"
    })
    public static class Bd {

        @XmlElement(name = "Informations", required = true)
        protected Bds.Bd.Informations informations;
        @XmlElement(name = "Image", required = true)
        protected Bds.Bd.Image image;
        @XmlElement(name = "Description", required = true)
        protected Bds.Bd.Description description;

        /**
         * Gets the value of the informations property.
         * 
         * @return
         *     possible object is
         *     {@link Bds.Bd.Informations }
         *     
         */
        public Bds.Bd.Informations getInformations() {
            return informations;
        }

        /**
         * Sets the value of the informations property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bds.Bd.Informations }
         *     
         */
        public void setInformations(Bds.Bd.Informations value) {
            this.informations = value;
        }

        /**
         * Gets the value of the image property.
         * 
         * @return
         *     possible object is
         *     {@link Bds.Bd.Image }
         *     
         */
        public Bds.Bd.Image getImage() {
            return image;
        }

        /**
         * Sets the value of the image property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bds.Bd.Image }
         *     
         */
        public void setImage(Bds.Bd.Image value) {
            this.image = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link Bds.Bd.Description }
         *     
         */
        public Bds.Bd.Description getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bds.Bd.Description }
         *     
         */
        public void setDescription(Bds.Bd.Description value) {
            this.description = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Description {

            @XmlValue
            protected String value;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Image {

            @XmlValue
            protected String value;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Titre" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Serie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Identifiant" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Scenario" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Dessin" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Couleurs" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Editeur" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ISBN" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "titre",
            "serie",
            "identifiant",
            "scenario",
            "dessin",
            "couleurs",
            "editeur",
            "format",
            "isbn",
            "date"
        })
        public static class Informations {

            @XmlElement(name = "Titre", required = true)
            protected String titre;
            @XmlElement(name = "Serie")
            protected String serie;
            @XmlElement(name = "Identifiant")
            protected int identifiant;
            @XmlElement(name = "Scenario", required = true)
            protected String scenario;
            @XmlElement(name = "Dessin", required = true)
            protected String dessin;
            @XmlElement(name = "Couleurs", required = true)
            protected String couleurs;
            @XmlElement(name = "Editeur", required = true)
            protected String editeur;
            @XmlElement(name = "Format", required = true)
            protected String format;
            @XmlElement(name = "ISBN", required = true)
            protected String isbn;
            @XmlElement(name = "Date", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar date;

            /**
             * Gets the value of the titre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitre() {
                return titre;
            }

            /**
             * Sets the value of the titre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitre(String value) {
                this.titre = value;
            }

            /**
             * Gets the value of the serie property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSerie() {
                return serie;
            }

            /**
             * Sets the value of the serie property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSerie(String value) {
                this.serie = value;
            }

            /**
             * Gets the value of the identifiant property.
             * 
             */
            public int getIdentifiant() {
                return identifiant;
            }

            /**
             * Sets the value of the identifiant property.
             * 
             */
            public void setIdentifiant(int value) {
                this.identifiant = value;
            }

            /**
             * Gets the value of the scenario property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScenario() {
                return scenario;
            }

            /**
             * Sets the value of the scenario property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScenario(String value) {
                this.scenario = value;
            }

            /**
             * Gets the value of the dessin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDessin() {
                return dessin;
            }

            /**
             * Sets the value of the dessin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDessin(String value) {
                this.dessin = value;
            }

            /**
             * Gets the value of the couleurs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCouleurs() {
                return couleurs;
            }

            /**
             * Sets the value of the couleurs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCouleurs(String value) {
                this.couleurs = value;
            }

            /**
             * Gets the value of the editeur property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEditeur() {
                return editeur;
            }

            /**
             * Sets the value of the editeur property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEditeur(String value) {
                this.editeur = value;
            }

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormat(String value) {
                this.format = value;
            }

            /**
             * Gets the value of the isbn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getISBN() {
                return isbn;
            }

            /**
             * Sets the value of the isbn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setISBN(String value) {
                this.isbn = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDate(XMLGregorianCalendar value) {
                this.date = value;
            }

        }

    }

}
